<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brand = 'Confort Time';

        $products = [
            // Refrigeradores Comerciales
            [
                'name' => 'Vitrina Refrigerada Confort Time VR-2400 Pro',
                'slug' => 'vitrina-refrigerada-confort-time-vr-2400-pro',
                'sku' => 'CT-VR2400-PRO-2024',
                'description' => 'Vitrina refrigerada profesional de 2.4 metros con sistema de iluminación LED y control digital de temperatura. Ideal para supermercados y tiendas de conveniencia. Incluye sistema de descongelación automática y puertas de vidrio templado.',
                'short_description' => 'Vitrina refrigerada profesional 2.4m con iluminación LED y control digital',
                'category_slug' => 'vitrinas-refrigeradas',
                'price' => 125000.00,
                'cost_price' => 95000.00,
                'sale_price' => 115000.00,
                'weight' => 280.50,
                'dimensions' => '2400x900x2000 mm',
                'model' => 'VR-2400 Pro',
                'specifications' => json_encode([
                    'Capacidad' => '2400 litros',
                    'Temperatura' => '0°C a 8°C',
                    'Potencia' => '2.5 kW',
                    'Voltaje' => '220V',
                    'Consumo' => 'A+',
                    'Material' => 'Acero inoxidable',
                ]),
                'is_active' => true,
                'is_featured' => true,
                'stock_status' => 'in_stock',
                'reorder_point' => 3,
            ],
            [
                'name' => 'Refrigerador Vertical Confort Time RV-1800 Elite',
                'slug' => 'refrigerador-vertical-confort-time-rv-1800-elite',
                'sku' => 'CT-RV1800-ELITE-2024',
                'description' => 'Refrigerador vertical comercial de 1.8 metros con tecnología inverter y sistema de gestión inteligente. Puertas de vidrio con sistema anti-empañamiento. Perfecto para bebidas y productos lácteos.',
                'short_description' => 'Refrigerador vertical 1.8m con tecnología inverter y gestión inteligente',
                'category_slug' => 'refrigeradores-verticales',
                'price' => 98000.00,
                'cost_price' => 75000.00,
                'sale_price' => 92000.00,
                'weight' => 195.00,
                'dimensions' => '1800x800x700 mm',
                'model' => 'RV-1800 Elite',
                'specifications' => json_encode([
                    'Capacidad' => '1800 litros',
                    'Temperatura' => '2°C a 8°C',
                    'Potencia' => '1.8 kW',
                    'Voltaje' => '220V',
                    'Consumo' => 'A++',
                    'Puertas' => 'Vidrio templado',
                ]),
                'is_active' => true,
                'is_featured' => true,
                'stock_status' => 'in_stock',
                'reorder_point' => 5,
            ],
            [
                'name' => 'Refrigerador Horizontal Confort Time RH-1200 Compact',
                'slug' => 'refrigerador-horizontal-confort-time-rh-1200-compact',
                'sku' => 'CT-RH1200-COMP-2023',
                'description' => 'Refrigerador horizontal compacto de 1.2 metros, ideal para espacios reducidos. Tapa de vidrio templado con sistema de cierre suave. Perfecto para carnicerías y pescaderías.',
                'short_description' => 'Refrigerador horizontal compacto 1.2m para espacios reducidos',
                'category_slug' => 'refrigeradores-horizontales',
                'price' => 65000.00,
                'cost_price' => 48000.00,
                'sale_price' => 59000.00,
                'weight' => 120.00,
                'dimensions' => '1200x800x900 mm',
                'model' => 'RH-1200 Compact',
                'specifications' => json_encode([
                    'Capacidad' => '1200 litros',
                    'Temperatura' => '-2°C a 4°C',
                    'Potencia' => '1.2 kW',
                    'Voltaje' => '220V',
                    'Consumo' => 'A+',
                    'Tapa' => 'Vidrio templado',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'stock_status' => 'in_stock',
                'reorder_point' => 4,
            ],

            // Congeladores
            [
                'name' => 'Congelador Vertical Confort Time CV-2000 Ultra',
                'slug' => 'congelador-vertical-confort-time-cv-2000-ultra',
                'sku' => 'CT-CV2000-ULTRA-2024',
                'description' => 'Congelador vertical de 2 metros con sistema de congelación rápida y tecnología no-frost. Puertas con cierre magnético y sistema de alarma de temperatura. Ideal para restaurantes y hoteles.',
                'short_description' => 'Congelador vertical 2m con sistema no-frost y congelación rápida',
                'category_slug' => 'congeladores-verticales',
                'price' => 110000.00,
                'cost_price' => 85000.00,
                'sale_price' => 105000.00,
                'weight' => 220.00,
                'dimensions' => '2000x750x700 mm',
                'model' => 'CV-2000 Ultra',
                'specifications' => json_encode([
                    'Capacidad' => '2000 litros',
                    'Temperatura' => '-18°C a -25°C',
                    'Potencia' => '2.2 kW',
                    'Voltaje' => '220V',
                    'Consumo' => 'A+',
                    'Tecnología' => 'No-Frost',
                ]),
                'is_active' => true,
                'is_featured' => true,
                'stock_status' => 'in_stock',
                'reorder_point' => 3,
            ],
            [
                'name' => 'Congelador Horizontal Confort Time CH-1500 Pro',
                'slug' => 'congelador-horizontal-confort-time-ch-1500-pro',
                'sku' => 'CT-CH1500-PRO-2023',
                'description' => 'Congelador horizontal tipo cofre de 1.5 metros con tapa abatible y sistema de cierre hermético. Perfecto para almacenamiento de grandes volúmenes de productos congelados.',
                'short_description' => 'Congelador horizontal 1.5m tipo cofre con tapa abatible',
                'category_slug' => 'congeladores-horizontales',
                'price' => 75000.00,
                'cost_price' => 58000.00,
                'sale_price' => 69000.00,
                'weight' => 180.00,
                'dimensions' => '1500x800x850 mm',
                'model' => 'CH-1500 Pro',
                'specifications' => json_encode([
                    'Capacidad' => '1500 litros',
                    'Temperatura' => '-18°C a -22°C',
                    'Potencia' => '1.5 kW',
                    'Voltaje' => '220V',
                    'Consumo' => 'A',
                    'Tapa' => 'Abatible hermética',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'stock_status' => 'in_stock',
                'reorder_point' => 4,
            ],

            // Refrigeradores Domésticos
            [
                'name' => 'Refrigerador Confort Time RT-350 Smart',
                'slug' => 'refrigerador-confort-time-rt-350-smart',
                'sku' => 'CT-RT350-SMART-2024',
                'description' => 'Refrigerador doméstico de 350 litros con tecnología Smart y conexión WiFi. Incluye pantalla táctil, control de temperatura por zonas y modo vacaciones. Diseño moderno con acabado en acero inoxidable.',
                'short_description' => 'Refrigerador doméstico 350L Smart con WiFi y pantalla táctil',
                'category_slug' => 'refrigeradores-dos-puertas',
                'price' => 85000.00,
                'cost_price' => 65000.00,
                'sale_price' => 79000.00,
                'weight' => 75.00,
                'dimensions' => '1800x600x650 mm',
                'model' => 'RT-350 Smart',
                'specifications' => json_encode([
                    'Capacidad' => '350 litros',
                    'Temperatura Refrigerador' => '2°C a 8°C',
                    'Temperatura Congelador' => '-18°C',
                    'Potencia' => '120W',
                    'Voltaje' => '220V',
                    'Consumo' => 'A+++',
                    'Tecnología' => 'Inverter',
                ]),
                'is_active' => true,
                'is_featured' => true,
                'stock_status' => 'in_stock',
                'reorder_point' => 6,
            ],
            [
                'name' => 'Refrigerador Confort Time RT-280 Eco',
                'slug' => 'refrigerador-confort-time-rt-280-eco',
                'sku' => 'CT-RT280-ECO-2023',
                'description' => 'Refrigerador doméstico ecológico de 280 litros con tecnología de bajo consumo energético. Incluye compartimento para frutas y verduras con control de humedad. Diseño compacto ideal para espacios pequeños.',
                'short_description' => 'Refrigerador ecológico 280L de bajo consumo energético',
                'category_slug' => 'refrigeradores-una-puerta',
                'price' => 55000.00,
                'cost_price' => 42000.00,
                'sale_price' => 52000.00,
                'weight' => 58.00,
                'dimensions' => '1500x550x600 mm',
                'model' => 'RT-280 Eco',
                'specifications' => json_encode([
                    'Capacidad' => '280 litros',
                    'Temperatura' => '2°C a 8°C',
                    'Potencia' => '90W',
                    'Voltaje' => '220V',
                    'Consumo' => 'A+++',
                    'Eficiencia' => 'Ecológico',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'stock_status' => 'in_stock',
                'reorder_point' => 8,
            ],
            [
                'name' => 'Refrigerador Confort Time RT-450 Side by Side',
                'slug' => 'refrigerador-confort-time-rt-450-side-by-side',
                'sku' => 'CT-RT450-SBS-2024',
                'description' => 'Refrigerador Side by Side de 450 litros con dispensador de agua y hielo. Sistema de filtración de agua integrado, iluminación LED y control de temperatura independiente por lado. Diseño premium.',
                'short_description' => 'Refrigerador Side by Side 450L con dispensador de agua y hielo',
                'category_slug' => 'refrigeradores-side-by-side',
                'price' => 145000.00,
                'cost_price' => 110000.00,
                'sale_price' => 135000.00,
                'weight' => 95.00,
                'dimensions' => '1800x900x700 mm',
                'model' => 'RT-450 Side by Side',
                'specifications' => json_encode([
                    'Capacidad Total' => '450 litros',
                    'Refrigerador' => '280 litros',
                    'Congelador' => '170 litros',
                    'Potencia' => '180W',
                    'Voltaje' => '220V',
                    'Consumo' => 'A++',
                    'Dispensador' => 'Agua y hielo',
                ]),
                'is_active' => true,
                'is_featured' => true,
                'stock_status' => 'in_stock',
                'reorder_point' => 4,
            ],

            // Aire Acondicionado
            [
                'name' => 'Aire Acondicionado Split Confort Time AC-12000 Inverter',
                'slug' => 'aire-acondicionado-split-confort-time-ac-12000-inverter',
                'sku' => 'CT-AC12000-INV-2024',
                'description' => 'Aire acondicionado split de 12,000 BTU con tecnología inverter y control WiFi. Incluye modo silencioso, filtro de aire HEPA y función de deshumidificación. Ideal para espacios de hasta 35 m².',
                'short_description' => 'Aire split 12,000 BTU inverter con WiFi y control inteligente',
                'category_slug' => 'aires-split',
                'price' => 125000.00,
                'cost_price' => 95000.00,
                'sale_price' => 115000.00,
                'weight' => 28.50,
                'dimensions' => 'Unidad interior: 800x300x200 mm',
                'model' => 'AC-12000 Inverter',
                'specifications' => json_encode([
                    'Capacidad' => '12,000 BTU',
                    'Área' => '35 m²',
                    'Potencia' => '1.1 kW',
                    'Voltaje' => '220V',
                    'Consumo' => 'A+++',
                    'Tecnología' => 'Inverter',
                    'Control' => 'WiFi',
                ]),
                'is_active' => true,
                'is_featured' => true,
                'stock_status' => 'in_stock',
                'reorder_point' => 5,
            ],
            [
                'name' => 'Aire Acondicionado Split Confort Time AC-18000 Turbo',
                'slug' => 'aire-acondicionado-split-confort-time-ac-18000-turbo',
                'sku' => 'CT-AC18000-TURBO-2024',
                'description' => 'Aire acondicionado split de 18,000 BTU con sistema turbo de enfriamiento rápido. Tecnología inverter, modo eco y filtro de aire avanzado. Perfecto para espacios comerciales de hasta 50 m².',
                'short_description' => 'Aire split 18,000 BTU con sistema turbo de enfriamiento rápido',
                'category_slug' => 'aires-split',
                'price' => 165000.00,
                'cost_price' => 125000.00,
                'sale_price' => 155000.00,
                'weight' => 35.00,
                'dimensions' => 'Unidad interior: 950x350x250 mm',
                'model' => 'AC-18000 Turbo',
                'specifications' => json_encode([
                    'Capacidad' => '18,000 BTU',
                    'Área' => '50 m²',
                    'Potencia' => '1.6 kW',
                    'Voltaje' => '220V',
                    'Consumo' => 'A++',
                    'Tecnología' => 'Inverter Turbo',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'stock_status' => 'in_stock',
                'reorder_point' => 3,
            ],

            // Partes y Repuestos
            [
                'name' => 'Compresor Confort Time COMP-5HP Scroll',
                'slug' => 'compresor-confort-time-comp-5hp-scroll',
                'sku' => 'CT-COMP5HP-SCROLL-2023',
                'description' => 'Compresor scroll de 5 HP para sistemas de refrigeración comercial. Alta eficiencia energética y bajo nivel de ruido. Compatible con refrigerantes R-404A y R-134a.',
                'short_description' => 'Compresor scroll 5 HP para refrigeración comercial',
                'category_slug' => 'compresores',
                'price' => 45000.00,
                'cost_price' => 32000.00,
                'sale_price' => 42000.00,
                'weight' => 25.00,
                'dimensions' => '400x300x350 mm',
                'model' => 'COMP-5HP Scroll',
                'specifications' => json_encode([
                    'Potencia' => '5 HP',
                    'Refrigerantes' => 'R-404A, R-134a',
                    'Voltaje' => '220V',
                    'Tipo' => 'Scroll',
                    'Eficiencia' => 'Alta',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'stock_status' => 'in_stock',
                'reorder_point' => 10,
            ],
            [
                'name' => 'Evaporador Confort Time EVAP-3000',
                'slug' => 'evaporador-confort-time-evap-3000',
                'sku' => 'CT-EVAP3000-2023',
                'description' => 'Evaporador de 3000 W para cámaras frigoríficas. Serpentín de cobre con aletas de aluminio. Incluye ventilador de alta eficiencia y sistema de descongelación automática.',
                'short_description' => 'Evaporador 3000W para cámaras frigoríficas',
                'category_slug' => 'evaporadores',
                'price' => 28000.00,
                'cost_price' => 20000.00,
                'sale_price' => 26000.00,
                'weight' => 18.50,
                'dimensions' => '800x600x300 mm',
                'model' => 'EVAP-3000',
                'specifications' => json_encode([
                    'Capacidad' => '3000 W',
                    'Material' => 'Cobre/Aluminio',
                    'Ventilador' => 'Alta eficiencia',
                    'Descongelación' => 'Automática',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'stock_status' => 'in_stock',
                'reorder_point' => 12,
            ],
            [
                'name' => 'Termostato Digital Confort Time TERM-DIGI Pro',
                'slug' => 'termostato-digital-confort-time-term-digi-pro',
                'sku' => 'CT-TERMDIGI-PRO-2024',
                'description' => 'Termostato digital profesional con pantalla LCD y control WiFi. Programación de horarios, alertas y registro de temperatura. Compatible con sistemas de refrigeración y congelación.',
                'short_description' => 'Termostato digital con WiFi y pantalla LCD',
                'category_slug' => 'termostatos-controles',
                'price' => 8500.00,
                'cost_price' => 5500.00,
                'sale_price' => 7800.00,
                'weight' => 0.35,
                'dimensions' => '120x80x30 mm',
                'model' => 'TERM-DIGI Pro',
                'specifications' => json_encode([
                    'Tipo' => 'Digital',
                    'Pantalla' => 'LCD',
                    'Control' => 'WiFi',
                    'Rango' => '-40°C a 50°C',
                    'Precisión' => '±0.5°C',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'stock_status' => 'in_stock',
                'reorder_point' => 15,
            ],

            // Refrigerantes
            [
                'name' => 'Refrigerante Confort Time R-134a 13.6 kg',
                'slug' => 'refrigerante-confort-time-r-134a-13-6kg',
                'sku' => 'CT-R134A-13.6KG-2024',
                'description' => 'Refrigerante R-134a de alta pureza en cilindro de 13.6 kg. Certificado y compatible con sistemas de refrigeración doméstica y comercial. Cumple con estándares internacionales.',
                'short_description' => 'Refrigerante R-134a de alta pureza 13.6 kg',
                'category_slug' => 'r-134a',
                'price' => 35000.00,
                'cost_price' => 25000.00,
                'sale_price' => 33000.00,
                'weight' => 13.60,
                'dimensions' => 'Cilindro estándar',
                'model' => 'R-134a 13.6kg',
                'specifications' => json_encode([
                    'Tipo' => 'R-134a',
                    'Peso' => '13.6 kg',
                    'Pureza' => '99.9%',
                    'Certificación' => 'ISO 9001',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'stock_status' => 'in_stock',
                'reorder_point' => 20,
            ],
            [
                'name' => 'Refrigerante Confort Time R-404A 10.9 kg',
                'slug' => 'refrigerante-confort-time-r-404a-10-9kg',
                'sku' => 'CT-R404A-10.9KG-2023',
                'description' => 'Refrigerante R-404A para sistemas de congelación comercial. Cilindro de 10.9 kg con válvula de seguridad. Ideal para congeladores y cámaras frigoríficas.',
                'short_description' => 'Refrigerante R-404A 10.9 kg para congelación comercial',
                'category_slug' => 'r-404a',
                'price' => 42000.00,
                'cost_price' => 30000.00,
                'sale_price' => 39000.00,
                'weight' => 10.90,
                'dimensions' => 'Cilindro estándar',
                'model' => 'R-404A 10.9kg',
                'specifications' => json_encode([
                    'Tipo' => 'R-404A',
                    'Peso' => '10.9 kg',
                    'Aplicación' => 'Congelación comercial',
                    'Certificación' => 'ISO 9001',
                ]),
                'is_active' => true,
                'is_featured' => false,
                'stock_status' => 'in_stock',
                'reorder_point' => 15,
            ],

            // Equipos de Cocina Comercial
            [
                'name' => 'Máquina de Hielo Confort Time ICE-50 Pro',
                'slug' => 'maquina-hielo-confort-time-ice-50-pro',
                'sku' => 'CT-ICE50-PRO-2024',
                'description' => 'Fabricadora de hielo comercial con capacidad de 50 kg por día. Sistema de producción continua, depósito de almacenamiento de 15 kg y filtro de agua integrado. Ideal para restaurantes y bares.',
                'short_description' => 'Fabricadora de hielo 50 kg/día con depósito de 15 kg',
                'category_slug' => 'maquinas-hielo',
                'price' => 95000.00,
                'cost_price' => 72000.00,
                'sale_price' => 89000.00,
                'weight' => 45.00,
                'dimensions' => '600x500x800 mm',
                'model' => 'ICE-50 Pro',
                'specifications' => json_encode([
                    'Producción' => '50 kg/día',
                    'Depósito' => '15 kg',
                    'Tipo de Hielo' => 'Cubos',
                    'Potencia' => '0.8 kW',
                    'Voltaje' => '220V',
                    'Filtro' => 'Integrado',
                ]),
                'is_active' => true,
                'is_featured' => true,
                'stock_status' => 'in_stock',
                'reorder_point' => 4,
            ],
        ];

        foreach ($products as $productData) {
            $category = Category::where('slug', $productData['category_slug'])->first();

            if ($category) {
                Product::create([
                    'name' => $productData['name'],
                    'slug' => $productData['slug'],
                    'sku' => $productData['sku'],
                    'description' => $productData['description'],
                    'short_description' => $productData['short_description'],
                    'category_id' => $category->id,
                    'price' => $productData['price'],
                    'cost_price' => $productData['cost_price'],
                    'sale_price' => $productData['sale_price'],
                    'weight' => $productData['weight'],
                    'dimensions' => $productData['dimensions'],
                    'brand' => $brand,
                    'model' => $productData['model'],
                    'specifications' => $productData['specifications'],
                    'is_active' => $productData['is_active'],
                    'is_featured' => $productData['is_featured'],
                    'stock_status' => $productData['stock_status'],
                    'reorder_point' => $productData['reorder_point'],
                ]);
            }
        }
    }
}

